### PR TITLE
WEB-3728 : Add Filter : Don't keep past events endpoint

### PR DESCRIPTION
**Pull request by boulch**
My dear @laulaz ,

This is an old needed feature.

https://support.imio.be/browse/WEB-3728?filter=-1

What do you think about that?
If events recurrence change some things about that... I think there will be time to change that in due time.

### CODE REVIEW

**Comment by laulaz** [comment]
@boulch this filter should be done / working on Events Authentic Source directly, to avoid sending old content.

The `event_dates` index is there for this purpose, see https://github.com/IMIO/imio.events.core/commit/e34e62b709631e40e95c13c7a7d1621bf30cde82

It should already work :thinking: ... see these query parameters : https://github.com/IMIO/imio.smartweb.core/blob/1d2c8c45bd0bcf72f01d1b0c6a4bc3fb41c13391/src/imio/smartweb/core/contents/rest/events/endpoint.py#L26-L27

We should probably debug that first, maybe there is no need for new "filtering" code.

**Comment by boulch** [comment]
[imio.smartweb.core/src/imio/smartweb/core/contents/rest/events/endpoint.py](https://github.com/IMIO/imio.smartweb.core/blob/1d2c8c45bd0bcf72f01d1b0c6a4bc3fb41c13391/src/imio/smartweb/core/contents/rest/events/endpoint.py#L26-L27)

This commit proves that we don't make a filter in Events Authentic Source directly (I'm an awful troll)

I saw this commit and I tried other ways to filter events... but nothing seems to work. 

In particular, this way (adding a new query parameter) : 
        query = {
            "i": "event_dates",
            "o": "plone.app.querystring.queryparser._afterToday",}

**Comment by laulaz** [comment]
It is not the Events Authentic Source that will filter by itself (it is indeed just an index) ... that was not what I meant 😉 
I meant that filtering should be done **on** Events Authentic Source, not after having received its results.

This is why we filter in the query, and not after the query ... but as you said there is maybe a bug in this query / results.

**Comment by laulaz** [comment]
Invalid and already developed. I close this PR 😉

**Pull request closed without merging**
